services:
  mongodb:
    image: 'mongo:4.4.18'
    ports:
      - '27017:27017'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 1s
      timeout: 1s
      retries: 1000
  adguard:
    image: 'adguard/adguardhome:latest'
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '8080:80'
    volumes:
      - './adg/workdir:/opt/adguardhome/work'
      - './adg/confdir:/opt/adguardhome/conf'
    healthcheck:
      test: [ "CMD", "wget", "http://127.0.0.1:80", "-qO", "/dev/null" ]
      interval: 1s
      timeout: 1s
      retries: 1000
  backend:
    build: 'backend'
    depends_on:
      mongodb:
        condition: service_healthy
    network_mode: 'host'
    command: 'gunicorn -b 0.0.0.0:5000 app:app --reload'
    volumes:
      - './backend/:/srv'
    healthcheck:
      test: curl -f http://localhost:5000/health_check
      interval: 1s
      timeout: 1s
      retries: 1000
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
  frontend:
    build: 'frontend'
    ports:
      - '80:8000'
    volumes:
      - './frontend/:/srv'
      - '/srv/node_modules'
      - '/srv/dist'
    healthcheck:
      test: curl -f http://0.0.0.0:8000/
      interval: 1s
      timeout: 1s
      retries: 1000