version: '3'

services:
  mongodb:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
  snifi:
    build: '.'
    depends_on:
      mongodb:
        condition: service_healthy
#    ports:
#      - '5000:5000'
    network_mode: 'host'
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW