version: '3'

services:
  mongodb:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
  snifi:
    build: '.'
    depends_on:
      mongodb:
        condition: service_healthy
    network_mode: 'host'
    command: 'gunicorn -b 0.0.0.0:5000 app:app --reload'
    volumes:
      - './:/srv'
    healthcheck:
      test: curl -f http://localhost:5000/health_check
      interval: 1s
      timeout: 10s
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW